[env:esp32dev]
platform = espressif32 @ 6.4.0
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

# LDF op deep is nodig om de standaard WebServer headers goed te vinden
lib_ldf_mode = deep

lib_deps =
    # Terug naar de stabiele WiFiManager
    https://github.com/tzapu/WiFiManager.git#v2.0.17
    # De standaard bibliotheken die bij het framework horen
    WebServer
    WiFi
    HTTPClient
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git    
    ESPmDNS
    Update
    FS

build_flags = 
    -D CORE_DEBUG_LEVEL=3